server:
  port: 8085

spring:
  application:
    name: clients-API

  datasource:
    url: jdbc:postgresql://localhost:5432/clients_db
    username: postgres
    password: ZXCvbn123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

